name: rlrisk
channels:
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - black
  - flake8
  - isort
  - pytest
  - pytest-cov
  - pre-commit
  - pip
  - ipdb
  - matplotlib
  - pytorch 
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - line_profiler
  - py-spy
  - pyinstrument
